version: "3.9"
services:
  user-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: customer_service
      POSTGRES_PASSWORD: customer_service
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
