name: AuthService CI / CD

on:
  push:
    branches:
      - master
    paths:
      - 'AuthService/**'
      - '.github/workflows/auth-service.yaml'
  workflow_dispatch:

jobs:
  build:
    name: 1. Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./AuthService/AuthService.sln

      - name: Build Project
        run: dotnet build ./AuthService/AuthService.sln -c Release --no-restore

      - name: Run Unit Tests
        run: dotnet test ./AuthService/AuthService.sln -c Release --no-build --verbosity normal

  deploy:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: ./MiniEcommerce/AuthService/AuthService.Api/Dockerfile 
          push: true 
          tags: ghcr.io/${{ github.repository_owner }}/authservice:latest 
