name: Deploy AuthService

on:
  push:
    branches:
      - master
    paths:
      - 'AuthService/**'
  workflow_dispatch:

jobs:
  call-template:
    uses: ./.github/workflows/service-ci-template.yml
    with:
      service-name: AuthService
      service-path: AuthService
