name: Deploy UserService

on:
  push:
    branches:
      - master
    paths:
      - 'UserService/**'
  workflow_dispatch:

jobs:
  call-template:
    uses: ./.github/workflows/service-ci-template.yml
    with:
      service-name: UserService
      service-path: UserService
