name: Deploy UserService

on:
  push:
    branches:
      - master
    paths:
      - 'MiniEcommerce/UserService/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: UserService

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build -c Release --no-restore

      - name: Run unit tests
        run: dotnet test -c Release --no-build

      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: userservice-artifact
          path: UserService/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: userservice-artifact

      - name: Deploy (customize this step)
        run: echo "🚀 Deploying UserService..."
